### ISSUE TITLE
Datapoints don't get overwritten when inserting different data types

### ISSUE THREAD

**Issue by FrEaKmAn** [kairosdb/kairosdb#162]
Hi

Today I noticed a very very very huge problem for me. It's happening with master and develop branch. The same (same time and tags) datapoints but with different value don't get overwritten. For example

```
put sensor.6.trend 1427076000000 1 name=STATUS\n
put sensor.6.trend 1427076000000 0 name=STATUS\n
```

When I query I get 1 datapoint with value 0

```
put sensor.6.trend 1427076000000 1 name=STATUS\n
put sensor.6.trend 1427076000000 0.0 name=STATUS\n
```

When I query, I get 2 datapoints: one with value 1 and other with value 0 (not 0.0, but 0). Same time, same tags, different value.

Normal?

**Comment by lcoulet** [comment]
Hi Erol, You are inserting different data types (int and float) so they belong to different series. 
The serializer put 0 instead of 0.0 but it's still a float that is been stored.

If you use the rest API you can make sure you push a double by telling it to KairosDB so the value gets overwritten. I don't think this is possible with the telnet API but it would not need a big change.

**Comment by FrEaKmAn** [comment]
Yes, but it makes no sense to have different values at same time for same tags.

**Comment by brianhks** [comment]
This has been part of Kairos from the beginning.  It comes from storing float values different from integer.  Each row of data is only stored one way.  We extended this functionality by adding the ability to store strings.  For the number types the aggregators will homogenize them together when reading.

In your case what you need to do is pick either float or int values and then send them all one way or the other.  The difference is if there is a "." in the value.  Send 0.0 will be float and 0 will be integer.

**Comment by FrEaKmAn** [comment]
But if I store 1.0, then I also expect 1.0 in the query results. But I get 1. 

But can someone tell me the situation where somebody will save 2 values at the same time for same tags?

**Comment by brianhks** [comment]
The 1 in the response is just a result of the serialization proess.  Internally the aggregators treat everything as a double.  What agregator are you using to get that result?

Yes I dont have a use case for storing 1 and 1.0 for the same time and tags.  It is a by product of the way we store the data.

**Comment by FrEaKmAn** [comment]
No. I made another test.

I inserted

    put sensor.8.trend 1427076000000 1.0 name=STATUS

and query

	{
	  "metrics": [
	    {
	      "tags": {},
	      "name": "sensor.8.trend"
	    }
	  ],
	  "cache_time": 0,
	  "start_absolute": 1425164400000,
	  "end_absolute": 1430344800000
	}

result is

    {"queries":[{"sample_size":1,"results":[{"name":"sensor.8.trend","group_by":[{"name":"type","type":"number"}],"tags":{"name":["STATUS"]},"values":[[1427076000000,1]]}]}]}

But lets take just one step back. Forget about the implementation. Will KairosDB ever be consider as serious contender if it has this kind of problem. Yes, for me it's a problem. I see combination of metric name and tags as primary key. There cannot be multiple primary keys, right?

**Comment by brianhks** [comment]
In reality the primary key is the metric name, tags, time and data type.  For example if you stored the string "hello" and then stored 1.0 for the same name, time and tags, you wouldn't expect it to overwrite "hello" right?

Internally we store double and long differently because we can store long in a lot less space than doubles so we have to make that distinction someplace along the line.

I would agree that if you insert as 1.0 you should get it back as 1.0.  But when performing aggregations we treat all values as double so if you insert 1, 2 you will get an avg back of 1.5.

As to the problem (storing multiple data points for the same time) there are two solutions:
1.  Make sure your application sends data the same way every time.  Pretty simple and most people are ok with this.
2.  Forgo the optimization of storing longs and store everything as double.  This could be done by supplying a new LongDataPointFactory that just called over to the DoubleDataPointFactory.  You could change the binding in the kairosdb.properties file.

2 is a little heavy handed as it will cause all data points to be stored in double form.

I'm open to any other suggestions.

**Comment by FrEaKmAn** [comment]
I would expect to overwrite "hello", because there cannot be 2 things at the same place at the same time, right? There is no way to differentiate "hello" and 1.0 with the query (to say only load Longs..)

I have completed custom logic for rollups. Basically I calculate history (from 5s to 10m) with external code. It's fired every day, calculates the values for 2 days (to overcome timezone problems) and if data changed, it saves it. Because it's update only operation, it's super fast and "light". Because I make queries and inserts/updates, I control the data type.

Now when we will have rollups built in KairosDB, we will probably create a query and save the results to new metric. What happens when we will get AVG = 2, then new datapoints will be added and AVG will become 2.3333 ...Inserting both will result in 2 datapoints. Should we actually do delete+insert? Can KairosDB automatically know the type of original datapoint? Should we have some settings for each tag to specify type? 

I totally understand the implementation, but I have a feeling that it will hurt KairosDB in the future.

Btw, do you know how much data in your case are Longs or Doubles. In our case, Longs represent less that 5% of data, so changing it to Double would not increase size too much.

**Comment by brianhks** [comment]
Lets address string data:  The original use case was to annotate data so "hello" should not overwrite 1.0.

Almost every aggregator converts the value to double before doing operations on the data.  So any data produced by an aggregator will be double.  When we do this internally the type is part of the datapoint so rollups will be stored as double.

In our use cases we have a lot of counter type data which stores much better as long than double.  I agree that this is a potential gotcha that I'll be addressing on the list periodically when someone hits it.  But the optimization on the backend outweigh the potential pothole is usability.
