### ISSUE TITLE
Nullable points not allowed - ...value may not be empty...

### ISSUE THREAD

**Issue by br0th3r** [kairosdb/kairosdb#164]
I don't understand why I can not save null points with KairosDB. A time-serie can finish in specific moment and start some time after. NULL points can define this no-information period of time.

`{'errors': ['metric[0](name=xxxxxyyyyyzzzzz).datapoints[6].value may not be empty.']}`

I think this should be allowed.

**Comment by brianhks** [comment]
Not sure I fully understand your use case.  You say you keep reporting but report null instead of a value?  Why not just stop reporting data?  The storage format right now prevents storing a null value, not sure how to represent that.

On the group there has been discussions of creating an aggregator that produces null output.  Maybe that is close to what you are after.

**Comment by br0th3r** [comment]
Yes, of course. We stop registering information when there is no information, but there is no way to save a STOP point, to say to the system we have stopped.

With no STOP point the database will always represent that no breakdowns ever happened at any time (what in my opinion is unbelievable).

One solution is to register a BASE value (like zero) or a MAX/MIN from the scale (MAX(DOUBLE) or similar) but this is not true since our data acquisition system knows there is NO DATA....this means the value it isn't 1, nor 100, nor 0.......

Doing a general analysis I think this is so questionable as '\0' is needed or not in a system (once you start working with any string you discover it is a must).

**Comment by FrEaKmAn** [comment]
I agree with Brian. It would be really strange to have null values. I think one of the ways is that you check if data is missing. Do you have datapoints in concise interval? The aggregator should be able to calculate missing values.

**Comment by br0th3r** [comment]
Answering to your question: "Why not just stop reporting data?" because we know there is NO DATA and we want to register in the database that we know we have NO DATA, that we weren't able to get any information from the source....let's give you an example:

Let's imagine a PING to a SERVER and it happened the next events (points to register):
12:00:00 - 134ms
12:00:03 - 133ms
12:00:05 - 145ms
---- The system BREAKs and STOP answering for 10 seconds (PING TIMEOUT) ---
12:00:18 - 145ms
12:00:21 - 147ms
12:00:23 - 137ms

with the actual method implemented in KAIROSDB the database will show up:
12:00:00 - 134ms
12:00:03 - 133ms
12:00:05 - 145ms
12:00:18 - 145ms
12:00:21 - 147ms
12:00:23 - 137ms

so analysing this information stored in the database it could happen 2 very different situations:

1) The process from 12:00:08 took longer than usually to write the data (it is just LAG...a DELAY, it could be a WARNING but not an ERROR)....the command locked for 10 seconds, there was high CPU, a interlock somewhere locked the reading or writting, KAIROSDB took longer to write (in a non-paralelized data-point registration system).

2) The processes (3 events) from 12:00:08, 12:00:11, 12:00:15 detected there is NO PING (it is a PROBLEM and we should know about it and it is definitely an ERROR) and should be registered (all of them or just one depends on the representation in the software that it is analizing the result).

Sincerely,

**Comment by br0th3r** [comment]
FrEaKmAn, in real life there are no "concise intervals". On industrial industry (factories, water analisys, energy, ....) you usually register as much as you can (as many times as possible) to have the most information as possible for after anlisys (compression is another subject, but it doesn't belong to KairosDB).

If you tell me that KairosDB doesn't register null values because it is better for performance, I will understand and close this subject. But I will fully disagree if you tell me you don't need null values for registering real life data.

**Comment by FrEaKmAn** [comment]
We use KairosDB for storing factory data and we log data every 5 seconds (avg values). For detailed analysis we log it every 100ms and for normal usage it's more than enough. Unless if you are in space exploration business or you're collaborating with CERN, then logging every 1ms is enough :)

You will anyway have to implement some additional logic that will check if data is not coming or if it contains null. You can store that in some database (start and stop datetime). Then you can use aggregator which inserts null for all time intervals. I think that having null values in KairosDB brings a bunch of new problems.

**Comment by br0th3r** [comment]
We don't work for CERN or space exploration, if you change in my example "ms" for "hours" the problem is still the same (even more notorious). We can use aggregators, I just wanted to know if it is like this to improve performance or it is just that you don't have this "kind of issues" in your systems: " I think that having null values in KairosDB brings a bunch of new problems".

In our company we also store factory data, I am just evaluating if we go straight to the database or use the great work you have done with KairosDB.

Sincerely,

**Comment by FrEaKmAn** [comment]
Don't get me wrong, we have the exact same problem. We notify responsible people in case if values reaches alarm value (for example if pressure is above maximum value). Not having the values means that we might skip it. We need to know how many times this happens.

We solve this by putting a lot of effort into logging. Also, we upload the data every 5 minutes (in batches) and check if there are datapoints missing. Because we log every 5 seconds, we can easily identify if data is missing because we always log tag STATUS. If we cannot obtain data, then we set status = 0. 

When we load the data, it will load the STATUS but of course it will not include missing datapoints. By tag status we know there should be some datapoints, so we can easily identify missing ones (we have custom KairosDB response parser which parses JSON into data structure similar to excel (rows and columns)). 

Again, don't get me wrong. On the end of the day Brian and Jeff are those who decide things, so if there is a need for null datapoints, the will be null datapoints. 

For the evaluating, I HIGHLY recommend KairosDB compared to other databases. The power and stability if just incredible. It has ton of great features (aggregators, REST) and it's easily extensible.

**Comment by brianhks** [comment]
After reading through your examples I think you can use the "string" data type to store start and stops of your data.  The way we store integer we would have to imply some value is null and that feels hackish.  We have optimized and minimized the data storage so there is no extra bits for signifying a null.

As I stated though you can use the "String" data type to store when a stream "starts" and "stops" by just inserting the string into Kairos.  Your application will have to read the string data and interpret it but that should work for you.  One of the original use cases for string data was to annotate the metrics.

Let me know if you need more information.

**Comment by br0th3r** [comment]
This is what we exactly have done, we have defined a specific character to represent NULL points and we have to reinsert this NULL points before processing, usually there are few of them. The solution it adds a O(n) complexity but it is not a problem at all.

Probably tomorrow we will be publishing some of the code we have coded for Grafana 2.0 KairosDB pluging resolving exactly this situation, so KairosDB users will be able to use Grafana 2.0 properly ( https://github.com/br0th3r/grafana2-kairosdb-datasource-plugin ).

We really like KairosDB and we are happy to have reached the same solution that you have proposed.

Thank you,
