### ISSUE TITLE
Support value filtering

### ISSUE THREAD

**Issue by arganzheng** [kairosdb/kairosdb#191]
We can filter by tag, but can not filter by value, for example, select metrics whose value > 100.

**Comment by FrEaKmAn** [comment]
Custom aggregator is an easy solution this problem. We could have a aggregator to which you pass the value and comparer (>, <, <=, >=, ==, ~)...

**Comment by lcoulet** [comment]
This is correct.
I will try to share our scripted aggregators with the community, one of
them is a filter that takes a predicate.
They perform pretty well but only work on Nashorn (Java 8), before that the
java JS engine (Rhino) was crap and too slow.

Predicate is javascript code or function can be based on value, or even can
be much more complicated.
e.g. value > 100, value%10==0 etc.

I'll try to make a PR next week.

Loic

2015-06-24 12:34 GMT+00:00 Erol <notifications@github.com>:

**Comment by Tomcat-Engineering** [comment]
This feature would be really useful to us if you are able to share the code.  Thanks!

**Comment by lcoulet** [comment]
I don't have the time to work on this until several weeks (I need to rework a little bit the relevant classes and to integrate them to Kairos base), I definitely won't have time until very long to put that in the UI (we have our own web UI that changed significantly from KairosDB).  
I propose to put the aggregator classes in a gist so someone else can integrate it into kairos. It shouldn't take very long. 
Any people interested in this proposition? - precision it will not work on Java < 1.8 because it's using Nashorn engine in protected mode, and doing the same with Rhino was inefficient and much more complicated to ensure safety.

**Comment by lentinj** [comment]
@lcoulet that would certainly be easier than starting from scratch, if you don't mind!

**Comment by lcoulet** [comment]
I have good news. I found some time to package the aggregators into an independent module and to put some documentation in a readme: 
https://github.com/Kratos-ISE/kise-kairosdb-module

As the module has more requirements from KairosDB (Java 1.8), I believe an optional module is a better approach.

Enjoy.

**Comment by lentinj** [comment]
Will try this in the next 2 weeks and report back. Sounds like a reasonable approach and should work fine for us.

Thanks for releasing!

**Comment by lentinj** [comment]
@lcoulet Yes, this seems to work nicely.

One small nitpick, a more descriptive name other than ``kise-kairosdb-module`` would be nice, but then it depends what else you intend putting in here.

**Comment by jsabin** [comment]
lcoulet has done a great job with these aggregators. Any reason to leave this issue open?

**Comment by lentinj** [comment]
@jsabin You might want the UI to support these options before you consider it done. However, there doesn't appear to be any easy way for a plugin to add to the default UI, and would be a fair bit of work.

**Comment by brianhks** [comment]
There is a filter agg that was added recently that takes care of this.
