### ISSUE TITLE
Diff aggregator returns value with the timestamp of the second data point

### ISSUE THREAD

**Issue by adedan** [kairosdb/kairosdb#213]
Using diff aggregator for monotonically increasing metrics (counters) should return the difference with the timestamp of the first data point and not of the second data point.

Example:
Data point A => 2015/08/01 00:00:00 value 200
Data point B => 2015/09/01 00:00:00 value 300

Current diff aggregator result:
2015/09/01 00:00:00 value 100

But the counter increment of 100 ticks was done in August so the result should be:
2015/08/01 00:00:00 value 100

**Comment by lcoulet** [comment]
I think the current behavior is exactly what most would expect.

If the increment is done in august, it cannot be visible by the first of august :)

We are using a time shift aggregator for this kind of usages. It's very easy to implement, buit maybe this is something we can share.

**Comment by adedan** [comment]
We're working in the energy monitoring domain and our customers expects to see their August consumptions at 2015/08/01. I understand for other domains it could be the opposite.

Can you please tell me how the time shift aggregator can be used to solve this problem?

**Comment by lcoulet** [comment]
Time shift reprocesses time stamps, it's a bit special. With this
aggregator we can for example realign data from different events. I'm not
sure it's widely useful enough to share with the community.

I can't see any logic for showing August consumptions the 08/01... I could
understand 08/31 or 09/01. But I personally would expect to see July
consumptions at 08/01 :)

You may also add your own version of diff aggregator that uses the first
timestamp. KairosDB modules are very easy to build.

**Comment by brianhks** [comment]
I also think the functionality is as expected by most - of course I'll say that because I wrote it that way ;)

Adding your own aggregator is pretty simple, the UI is the only icky part - which I would love to know of a way to make better.  Here is the diff aggregator code: https://github.com/kairosdb/kairosdb/blob/develop/src/main/java/org/kairosdb/core/aggregator/DiffAggregator.java

I should create a sample project people can clone for making aggregators.  The https://github.com/kairosdb/kairos-kafka project is a good one to start with.

**Comment by plap979** [comment]
Ok, I'll implement my own aggregator too. But, please, let me understand...

Let say that you read your electricity meter counter on August 1st and it reports 500 kWh, then you read it again on September 1st and it reports 650 kWh. Finally do you say that you consumed 150kWh in September? 

Or what that aggregator worth for?
