### ISSUE TITLE
Cassandra Compaction Strategy

### ISSUE THREAD

**Issue by warmans** [kairosdb/kairosdb#23]
We been experiencing the following issue: 
Large amounts of data is logged over the course of the day or night. The first query that is run which touches any of this new data will trigger compactions across the entire cassandra cluster. This first query will be rejected by cassandra with a timeout exception (same as this: http://stackoverflow.com/questions/6514343/cassandra-hector-timeouts-what-to-do).
Once all new data has been "touched" it will become query-able reliably.

It would seem this is related to the fact that kairos assumes the default compaction strategy (size tierd). This apparently not the best strategy for update-heavy workloads (i.e. kairos' wide rows): http://www.datastax.com/dev/blog/when-to-use-leveled-compaction

We have manually altered our keyspace to use leveled compaction and are have already seen our data size fall by three quaters (down to around 100GB from 400). We have yet to observe any timeout exceptions with this strategy but haven't had any long periods of query inactivity so cannot make any judgements just yet.

Anyway. I believe the cassandra defaults may need some investigation or input from others who have manually altered their config to reach a more optimum configuration for large workloads.

**Comment by AeroNotix** [comment]
I'm using DTCS with Kairos with a 3 day TTL and I'm seeing a steady increase of data, not a "three day working set" as I would've imagined that I would've had. 

Does any one have any input here?

**Comment by warmans** [comment]
Has it been more than 3 days since you made the change? TTLs only affect new values as the TTL is applied on the way in.

**Comment by AeroNotix** [comment]
It's been 3 months.

**Comment by AeroNotix** [comment]
I'm running 2.0.13, these tickets suggest that DTCS in 2.0.13 has several compaction issues:

https://issues.apache.org/jira/browse/CASSANDRA-8360
https://issues.apache.org/jira/browse/CASSANDRA-8369

**Comment by AeroNotix** [comment]
After upgrading to 2.0.16: https://db.tt/MlmGnvGJ

**Comment by farzadpanahi** [comment]
Any plan on making DTCS the default compaction strategy for kairosdb?

**Comment by carysyd** [comment]
Hey guys, I found this thread talking about Cassandra compaction strategy for KairosDB and want to see if you any of you have the same problem as me. 

So I'm using LCS for KairosDB, with data point TTL set to 5 weeks.

It works well in the first week. With regular small compactions it helps to throw away stale data points. However, as the level grows, my data set start growing because some old SSTables don't get a chance to be compacted. I had to run major compaction regularly. Major compaction is slow and there seems to be no way to speed it up even if the host has spare CPU and IO resources.

Any suggestion?

**Comment by AeroNotix** [comment]
Why are you running LCS?

**Comment by carysyd** [comment]
@AeroNotix Our workload reads quite often, from my understanding LCS is more suitable for frequent reads. That being said, switching compaction strategy is an option for us as long as it works better.

However, looking at STCS and LCS, in theory, they can all get into this scenario where SSTable becomes very big and won't be compacted due to compaction policy. As a result, stale data points stays and we had to provision much much bigger disk space.

Can anyone share some thoughts and feedbacks on the DTCS or other compaction strategies?

**Comment by AeroNotix** [comment]
I don't run Cassandra in production any more but I remember with our workload which was reasonably large w/ a TTL of 3 days before/after introducing DTSC was a huge difference, read back in the thread to see an image of it.

I would recommend it if your TTL is low, I would suggest doing extensive tests if your TTL is 5 weeks though.

**Comment by brianhks** [comment]
From my reading and comments from others the prefered strategy is TWCS over DTCS.  I've been using it in non production applications and it seems to work well.  I haven't tested out the ttl functionality though.

For what it is worth in a different application that I run (not kairos) we ttl our data at 2 weeks - about 300TB of data currently in the cluster and LCS works really well.  Disks are running around 80% of capacity and it churns through the data nicely.

**Comment by raffraffraff** [comment]
@brianhks any update on your last comment? The thing that interests me most about DTCS is that it stores data written within a certain period of time in the same SSTable. With expiring data, the benefit is that all the data in an SSTable will be scheduled to expire at roughly the same, so Cassandra can drop the SSTable without doing any compaction. That sounds like a great way to reduce random IO on cheaper spinning disk. Also, for people running an older Cassandra cluster, TWCS may not be available.
