### ISSUE TITLE
Intensive reads lead to huge memory consumption

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#241]
Hello.

I'm using kairosdb 1.1.0 and cassandra 1 node cluster (both are placed on separate virtual machines). 
Writes are fast enough and do not consume much memory. However read requests over the time use all the available memory.

Right now I have 50 clients that make 1 request per second (100 points) from one metric (with no tags). 
It usually works well for about one hour until all the available heap is not consumed. I see about 2 GB memory growth.
As soon as it is close to the limit of Java heap size, Kairosdb throws the following exception: "org.kairosdb.util.MemoryMonitorException: Insufficient memory to perform"

The heap size is 2GB, but I tried to increse it to 4GB, but it did not help. All in all, the entire heap size was consumed. 

Could you tell me how to struggle with this ? Why so much memory is used by Kairosdb as I'm not reading to much data ?
How much memory I need (especially considring the fact that I'm going to make much more read requests) ?

Could someone also can clarify what the cache files are used for in Kairosdb ?

Here are some my config values:

kairosdb.datastore.concurrentQueryThreads=100
kairosdb.datastore.cassandra.write_delay=100
kairosdb.datastore.cassandra.write_buffer_max_size=50000000
kairosdb.datastore.cassandra.single_row_read_size=10240
kairosdb.datastore.cassandra.multi_row_size=1000
kairosdb.datastore.cassandra.multi_row_read_size=1024
kairosdb.datastore.cassandra.row_key_cache_size=10240
kairosdb.datastore.cassandra.string_cache_size=10000

The graphics below are very confused, looks like JVM has enough free memory, but it actually doesn't.

![jvm free_memory](https://cloud.githubusercontent.com/assets/4169171/11334089/b43ab446-91e3-11e5-9a2f-f0c4def99062.png)
![jvm total_memory](https://cloud.githubusercontent.com/assets/4169171/11334091/b6b898d2-91e3-11e5-914b-c8c8cc54c74e.png)

**Comment by lcoulet** [comment]
Hi, I don't see any problem from the screens you sent. There's no reason
for KairosDB to consume high memory with such small requests.

What JVM Implementation are you using?


2015-11-23 11:13 GMT+01:00 Khorev Ilya <notifications@github.com>:

**Comment by weirdy** [comment]
Thanks, lcoulet.

I've installed 64bits JDK insead of 32bit JRE and looks like it has solved the memory issue, at least for now.

I am now using 60 clients, each one is reading 1000 points per second.
I have noticed that read requests have become slower in comparison with the situation when 10 clients are working simalteneously. Could you advice what should I do to make them faster ?
Will increasing of concurrentQueryThreads config setting help me with that ? Or I should increase the number of Cassandra nodes to fit this performance requirements ?

What does Kairosdb store in cache files ? Is it ok to configure the job to clean them every 10 minutes ?
How does it influence on performance ?

**Comment by weirdy** [comment]
I also find out that when there are many clients writing the data intensivly - everything is fine. However, when mulitple clients write and read data simultaneously, both reads and writes become much much slower.
Looks like some requests are blocked by other requests... Any advices ?

**Comment by brianhks** [comment]
As a side note I'm really interested in your use case, why do the clients all query so often?

Cache files:  The data from cassandra has to be sorted by time in order to be processed by the aggregators.  The rows we get back from C* are each individually sorted by each row can cover the same time span.  Kairos writes the data from C* to disk (cache file) and then reads it in sorted order to be processed by the aggregators.  If all of your machines are querying the same data (which sounds like you are) you can use the cache_time parameter to read from cache instead of going to C* every time.  If you set the cache_time to 5 then if the same query was made within the last 5 sec it will reuse the cache data and skip C* (way faster).  Clean them as often as you like.

A good read on all this is https://github.com/kairosdb/kairosdb/wiki/Query-Performance it will give you some insight into what Kairos does along with some metrics you can use to figure out what is slow.

Also if the queries are the same they will collide and wait for the previous one to finish causing collisions that are slowing them down.  If these queries were hitting different metrics or had different tags then C* would become your bottleneck and you can fix that by growing the cluster.

Check kairosdb.datastore.query_collisions metric to see if you have collisions.

Brian

**Comment by weirdy** [comment]
Thanks brianhks.

This is just a production requirement of the software I am developing. I don't know why they need to query data so often.

Regarding my use use, let my clarify this again. Each client writes and reads its own metric. Each client reads 1000 points every second from one metric using a different time interval. So all machines queries each time different data from different metrics and cache_time will not solve my issue.

Am I right in saying that Kairos first reads the points from C*, than writes this data to the file, than reads it in a sorted order from the file and after that sends to the client ? Would it be better to use SSD in my case instead of HDD ?
Also I would like to mention that each client in my case is querying the data from one metric (with no tags) and looks like I don't need the points received from C* are stored in these files, because I don't need preprocessing or aggregating. Can I somehow disable this functionality and return data straight away to the clients as soon as it is received from C* ?

How does it work internally, each query request is processed by individual thread in Kairos ?

I've checked the kairosdb.datastore.query_collisions metric, looks like I didn't have any collisions. 

I also don't understand why over the tme, when clients continue to query the data, writes become slower and slower. In my case writes are 10x slower when the clients intensively queries the data.
Do I need to adjust some configuration parameters ?

**Comment by weirdy** [comment]
I'm stille experiencing this issue, reads become quite slow after some period has elapsed. Looks like query threads block each other. Could someone describe in detail how concurrent reading works in Kairos?
Thanks in advance.
