### ISSUE TITLE
Create option for choosing second granularity in Cassandra

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#246]
Taken from this conversation: https://groups.google.com/forum/?hl=en#!topic/kairosdb-group/k0rgI8w8DuE

Create a way to switch Cassandra to store data with second granulaity.  Basically making the rows 1000 times larger.  The use case is for users who want to store data with one day granularity.

**Comment by gary-yang** [comment]
This would be really useful for our use case too. We are storing data at second granularity and would like to pack more data into one row.

**Comment by muglar** [comment]
I third this request !

**Comment by gzkevinl** [comment]
I really want this feature as well.

**Comment by cbornet** [comment]
+1 . This is a major enhancement for IoT where the sensor precision itself is often not sub-milli and you want to make analysis over long periods of time (several years).

**Comment by raffraffraff** [comment]
+1 _Really_ interested in this. I'd like to test the effects of a reduced  granularity (1 second). I assume it can't be 'hacked' in place by modifying the data_points table schema in Cassandra.

**Comment by raffraffraff** [comment]
I may be (probably am) wrong but didn't ZMON achieve something like this in
their kairosdb fork, keeping it backward compatible?

**Comment by raffraffraff** [comment]
Apologies, I am wrong. They tuned row widths.

https://groups.google.com/forum/m/#!topic/kairosdb-group/lTa5p7Q_qyk

write_row_width 3 days
read_row_width 3 weeks
This queries properly for existing data in old wide rows and also reads
data from newer smaller ones.

They did this because they've got high tag cardinality, and 3 day width
quickly removes unused tag combinations.

**Comment by jdursel** [comment]
@raffraffraff thank you for the search! It can eventually be useful for one of our high cardinality use case.

**Comment by mamoit** [comment]
Our use case actually calls for the exact opposite of this.
We need to be able to store data with nanosecond granularity (frequency can go as high as 25kHz).

**Comment by fbeneventi** [comment]
+1

**Comment by mrdgrobler** [comment]
+1 from another Iot user

**Comment by robshep** [comment]
Hi,
I've been poking around looking to try and implement this.  
I've got a naive implementation worked out, you might like to take a look.

I've made a DataRowTimeService that handles a variable time resolution and row width. 

In order to support all the existing system metrics I've done a cheap trick of  switching on the metric name.... if it starts with "kairosdb." then (i assume) it's a system metric and that'll keep on using the default 3wks@1ms resolution.... otherwise the configurable resolution and width is used. 

Nevertheless, It's conceivable to support various different resolutions concurrently based on metric prefixes like this. 

It needs a heck of a lot of testing and evaluating. it's a WIP at present. Take a look.

https://github.com/kairosdb/kairosdb/compare/develop...robshep:iss246timeres?expand=1

**Comment by robshep** [comment]
a docker image of the above, map a conf file in with the params to give it a go.
https://hub.docker.com/layers/evometric/kairosdb/1.3.0b1-timeres1/images/sha256-e35411c52de779aaa0c0b340236b0daaa53fa934dcd804eca9022e650c9529b2?context=repo

**Comment by brianhks** [comment]
I looked through your changes and I like the idea of the service.  It would let others implement their own strategy for changing the row width.  I think for the default I'll add a configuration on the cluster.  I'll think about this some more.

**Comment by robshep** [comment]
Let me know if the implementation so far is satisfactory and I'll keep adding tests.  Keen to help get 1.3 over the line

**Comment by robshep** [comment]
I did think that user configuration might be best done by presets.  Certainly the developers here know more about the internals and performance considerations and ( as with my impl ) a novice user _might_ pick something daft and be stuck with it. Bundling a preset mix of resolutions/row_widths will make easier to initially pick a config to align with the pattern of the metric ingress

- RES_PRESET_1ms_3wk
- RES_PRESET_25ms_500d
- RES_PRESET_1sec_20yr

You get the idea.

**Comment by brianhks** [comment]
What you said is why I like attaching it to the cluster somehow.  People may not realize what they are up against when they start and will want to change it.  Rolling to a new cluster with a different config will allow them to make those changes on the fly and still be able to keep old data.  But having some presets is a good idea as well.  I'll keep thinking about it.

**Comment by robshep** [comment]
What can I do to help with this further.
I’d like to help get 1.3 over the line?

**Comment by brianhks** [comment]
So I was able to get this into the code.  It lets you change the granularity (seconds vs milliseconds) and the row width for new write clusters.  I added a new table to keep track of what the cluster is set to so users cannot screw up a cluster once it is set.
