### ISSUE TITLE
Introducing LMAX disruptor in MemoryQueueProcessor to improve performance

### ISSUE THREAD

**Issue by wanglingsong** [kairosdb/kairosdb#375]
Here is the performance comparision between disruptor ringbuffer and arrayblockingqueue:
https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results

**Comment by brianhks** [comment]
I've looked very seriously at the disruptor code.  I've done something similar in the CQL branch.  At this point the bottleneck is with sending data to C* and not in my queue processor.

**Comment by lcoulet** [comment]
Just to point that this issue seems irrelevant (and  probably overkill) to me. Moreover what performances would it try to improve?  Queries or pushes, or both? And why do you believe would it improve performances?
From my measurements two major performance bottlenecks are ion that order:
- on queries: Cassandra then JSON serialization (if a lot of data is returned)
- on push: JSON parsing then Cassandra. But adding kairosDB (and C*) nodes solve all possible issues on push.
 
Note that JSON parsing and serialization is quite fast considering what is being done.  Even if we send over large gzipped JSON files, it works like a charm. 

Agreed that Cassandra is not very fast. On every aspect Cassandra falls behind KairosDB, but Cassandra is nonetheless a great distributed database.
