### ISSUE TITLE
Sampler aggregator - improper behaviour?

### ISSUE THREAD

**Issue by lcoulet** [kairosdb/kairosdb#378]
By looking at the sampler aggregator code (which should calculate a time-boxed derivative), its behaviour seems improper to me.

Code:
`double rate = x1 / (y1 - y0) * Util.getSamplingDuration(y0, m_sampling, m_timeZone);
return (m_dataPointFactory.createDataPoint(y1, rate));`

As the previous known valus is ignored, the result seems meaningless (same as derivative with always zero as previous value).

I would expect the following calculation:
`double rate = (x1-x0) / (y1 - y0) * Util.getSamplingDuration(y0, m_sampling, m_timeZone);`

**Comment by ehocdet** [comment]
@jsabin Sampler aggregator is correct. What you expect is in Rate aggregator.

**Comment by brianhks** [comment]
I've looked at this code and the definition of a sample rate and this is my conclusion.  The sample rate is how many of some occurrence happens per second, millisecond, etc.  Lets say the metric is reporting cars on the freeway since last reported, but it also reports very irregularly.  This aggregator could report cars per minute.  Now if the car count was reported as an ever increasing counter than the rate aggregator would be used.  At least that is my understanding so it looks right and I'll close this
