### ISSUE TITLE
Question about changing partition size

### ISSUE THREAD

**Issue by infordb** [kairosdb/kairosdb#392]
I am trying to use scylladb as a repository for kairodb  (http://www.scylladb.com/)
scylladb recommends a partition size of 10MB or less.
so I want to change  time period of 21 days for data point partition size
How do I do it ?

**Comment by brianhks** [comment]
It is hard coded to 3 weeks, you would have to recompile the code, but it isn't worth it.  Kairos partitions the data by metric name, tag and type of data.  You would have to insert a data point every 3 seconds with exactly the same metric name and tags in order to come close to the 10mb limit.  Also in the 1.3 they claim better support for large partitions.

**Comment by infordb** [comment]
@brianhks  I am planing to insert a data point every seconds or 100 milliseconds
Do you have a plan that  user can set the partition size in kairosdb.properties?

**Comment by brianhks** [comment]
The problem is that the setting is not something you change on the fly.  If you set it to one week it must forever be set to one week.  All the calculations for inserting and querying are based on this value.

The value is set in CassandraDatastore.java as ROW_WIDTH.  You can change it but you will have to recompile and maintain the fork yourself.

**Comment by michaelsembwever** [comment]
@brianhks 
It is unfortunate that KairosDB doesn't realise the importance of making this configurable. 

There is a trade-off between response size and the number of asynchronous requests executed here. For example a smaller partition bucketing window would mean more asynchronous requests have to be spawned (when the query spans more than one bucketing window), but each request would have lower latency. The query latency is only the slowest of all the asynchronous requests so will likely be resolved faster, so long as the cluster is able to serve the increased request throughput. 

In a KairosDB installation I'm looking at there are partitions of over 10GB. Even on Cassandra-3.11 that deals with wide partitions: see the [blog](https://thelastpickle.com/blog/2019/01/11/wide-partitions-cassandra-3-11.html) post I wrote; these partitions can not be read from, the read requests time out. These partitions are also impacting latencies of other requests during background compaction and streaming operations. As mentioned in https://github.com/kairosdb/kairosdb/issues/148 these partitions are from kairosdb's internal metrics, so it's hard to even argue that it's only the user abusing the data point frequency.

I understand the difficulty in changing this setting in a running production environment, without wiping the data, but I suspect that even a bucketing strategy of one day would provide more stable and scalable installations. At the minimum I would recommend some benchmarking across the trade-offs to better sell the hardcoded value you have.

**Comment by brianhks** [comment]
@michaelsembwever you make some good arguments.  Problem is I'm kind of stuck with the setting for now.  Although I could see adding exceptions for specific metrics that you call out in the configuration.  Then if you wanted to change it you could role to a new cluster with the metric set for a different bucket size.
