### ISSUE TITLE
How to get the first datapoint in the time-series ? 

### ISSUE THREAD

**Issue by Abouzeid** [kairosdb/kairosdb#481]
Hi everyone,
 
I want to discover the most recent recorded data-point, and the first added one.
In KairosDB, the **first** and the **last** aggregators need an interval and a start data-time. But, I don't know the first data-point time-stamp nor the latest one.

Any help will be appreciated.
Thanks

**Comment by lcoulet** [comment]
Hello, the most efficient is to use limit and order (cf. https://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html)

- By querying data from beginning of life to now with limit=1 it will fetch the very first sample.
- By querying data from beginning of life to now with limit=1 and order=desc it will fetch the very last 
sample.

Otherwise you can ask for the first or last aggregator on a 100 years or so time span, but it will require to fetch all the data, it is way less efficient.

I recommend you ask this kind of questions on the kairosDB discussion group: https://groups.google.com/forum/#!forum/kairosdb-group

**Comment by Abouzeid** [comment]
I still need to provide the time span.
Got it.
Thanks @lcoulet
