### ISSUE TITLE
Non-linear sampling/multiple time ranges?

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#533]
How do I get this to work with multiple time ranges or multiple aggregators on the same range of datapoints?

Mutliple aggregators just pipe into each other and using the same metric more than one with start time produces inexplicable results (it includes results outside of the start time).

**Comment by joeyhub** [comment]
The basic issue here is that if you need to do multiple arbitrary slices of a span like: from a to b take [15%, 15%, 5%, 10%, 30%, 25%] then get the product of each of those then you have to make multiple queries.

That's fine though it can be confusing to reach the point you realise you need to do that that in the documentation. KairosDB's querying supports a very restricted subset of operations which I found wasn't immediately discernible from the documentation.

An area of particular confusion is in your aggregators. You have all these mutually exclusive fields for align and then start_time which as far as I can tell is actually align_time. It's not named what anyone looking at it might expect it to be.

If you make a v2 of the API it would be less confusing to have: `{"alignment": "type"}` where type might be start, end, unit or absolute or relative. Then based on what's there you might bring other fields into play like align_time or align_unit.

**Comment by brianhks** [comment]
The documentation has been updated in the source.
* align_sampling - An optional property. Setting this to true will cause the aggregation range to be aligned based on the sampling size.  For example if your sample size is either milliseconds, seconds, minutes or hours then the start of the range will always be at the top of the hour.  The effect of setting this to true is that your data will take the same shape when graphed as you refresh the data. This is false by default.
* align_start_time - An optional property. When set to true the time for the aggregated data point for each range will fall on the start of the range instead of being the value for the first data point within that range. This is false by default.
* align_end_time - An optional property. Setting this to true will cause the aggregation range to be aligned based on the sampling size. For example if your sample size is either milliseconds, seconds, minutes or hours then the start of the range will always be at the top of the hour. The difference between align_start_time and align_end_time is that align_end_time sets the timestamp for the datapoint to the beginning of the following period versus the beginning of the current period. As with align_start_time, setting this to true will cause your data to take the same shape when graphed as you refresh the data. Note that align_start_time and align_end_time are mutually exclusive. If more than one are set, unexpected results will occur.

That has been kind of confusing in the past if you have any suggestions for making it better I would welcome it.  All the docs are in the source project and I'll take pull requests on any changes you feel would make it clearer.

As for a V2 I'm cooking one up.  If I understand you correctly you want to take the same set of data and run it through different sets of aggregators.  The new query will allow for that.
