### ISSUE TITLE
NoSpamLogger.java:94 - Unlogged batch covering 57 partitions detected against table [kairosdb.data_points]. You should use a logged batch for atomicity, or asynchronous writes for performance.

### ISSUE THREAD

**Issue by gavinju** [kairosdb/kairosdb#563]
After starting the Kairosdb service, the Cassandra service has a lot of warning messages:
NoSpamLogger.java:94 - Unlogged batch covering 57 partitions detected against table [kairosdb.data_points]. You should use a logged batch for atomicity, or asynchronous writes for performance.

The version info is:
apache-cassandra-3.11.4-bin.tar.gz  
kairosdb-1.2.2-1.tar.gz

**Comment by brianhks** [comment]
I think there may be a way to turn those warnings off.  Despite what it says I'm using the fastest mechanism to write data to C*.  And because all of my writes are idempotent I can resend the entire batch if something fails and it will all work out just fine.  I've spent hours researching/testing this so you can just ignore the warning.
