### ISSUE TITLE
Rollup Task always returns data point count of zero

### ISSUE THREAD

**Issue by Abouzeid** [kairosdb/kairosdb#588]
KairosDB 1.2.2-1.20181109205636
Cassandra: 3.11.5

Log output:
Rollup Task: [Name] for Rollup [save_as_meteric] data point count of 0

Create Roll up JSON
![image](https://user-images.githubusercontent.com/9715386/70785886-5bda8880-1dc6-11ea-889d-1faa258cd18d.png)

When I run the query, using the query metrics REST API, it returns the values correctly. However, the rollup task for the same query doesn't write any data points to the save_as metric.

Here is the query which returns a result of 64 datapoints
![image](https://user-images.githubusercontent.com/9715386/70786357-78c38b80-1dc7-11ea-9999-e336134b74fa.png)

Any help will be appreciated.

**Comment by kyleboyle** [comment]
Try turning on debug for rollup logs to see actually start / end samples generated and rollup duration:
 <logger name="org.kairosdb.rollup" level="DEBUG"/>

I suspect the issue is with your execution interval 1m vs your rollup period of 1 day. The rollup logic currently only queries for samples since the last run, which in your case would be 1 m ago.

**Comment by Abouzeid** [comment]
1. As suggested , I did add the line `<logger name="org.kairosdb.rollup" level="DEBUG"/>` to logback.xml file. I hope that's the right place for it.
![image](https://user-images.githubusercontent.com/9715386/70874820-d554bf80-1fee-11ea-989d-654f5aec0652.png)

2. After making the execution interval equal to the rollup period, the datapoints got written to the save_as metric. 
"**The rollup logic currently only queries for samples since the last run**" That explains a  lot.
